using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using QuestPDF.Drawing;
using ContainerDelivery.Core.Entities;
using ContainerDelivery.Core.Enums;

namespace ContainerDelivery.Infrastructure.Reports;

/// <summary>
/// Standalone QuestPDF report generator for Container Delivery.
/// Can be used independently without the full infrastructure.
/// </summary>
public class ContainerDeliveryReport : IDocument
{
    private readonly ContainerData _container;
    private readonly List<VehicleData> _vehicles;
    private readonly string _generatedBy;
    private readonly string _companyName;

    public ContainerDeliveryReport(
        ContainerData container, 
        List<VehicleData> vehicles, 
        string generatedBy, 
        string companyName = "Container Delivery System")
    {
        _container = container;
        _vehicles = vehicles.OrderBy(v => v.Description).ToList();
        _generatedBy = generatedBy;
        _companyName = companyName;
    }

    public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Margin(40, 50, 40, 50);
            page.PageColor(Colors.White);
            page.DefaultTextStyle(x => x.FontFamily("Helvetica").FontSize(10).FontColor(Colors.Grey.Darken2));
            
            page.Header().Element(ComposeHeader);
            page.Content().Element(ComposeContent);
            page.Footer().Element(c => ComposeFooter(c));
            
            page.Layer(LayerName.Watermark).Element(c => 
            {
                c.Rotate(-45).AlignCenter().AlignMiddle()
                    .Text("CONFIDENTIAL")
                    .FontSize(72)
                    .FontColor(Colors.Red.Lighten1.WithAlpha(0.1f))
                    .Bold();
            });
        });
    }

    void ComposeHeader(IContainer container, Container reportContainer)
    {
        var primaryColor = Colors.Blue.Darken2;

        container.Row(row =>
        {
            row.RelativeItem().Column(col =>
            {
                col.Item().Row(r =>
                {
                    r.AutoItem().Width(50).Height(50).Background(primaryColor)
                        .AlignCenter().AlignMiddle()
                        .Text("📦").FontSize(24).FontColor(Colors.White);
                    r.RelativeItem().PaddingLeft(10).Column(c =>
                    {
                        c.Item().Text(_companyName).FontSize(22).Bold().FontColor(primaryColor);
                        c.Item().Text("VEHICLE DELIVERY REPORT").FontSize(11).FontColor(Colors.Grey.Medium).LetterSpacing(1);
                    });
                });
                
                col.Item().PaddingTop(10).Row(r =>
                {
                    r.AutoItem().Text($"Container: ").SemiBold().FontSize(11).FontColor(Colors.Grey.Darken1);
                    r.AutoItem().Text(_container.ContainerNumber).FontSize(18).Bold().FontColor(primaryColor);
                    r.ConstantItem(20);
                    r.AutoItem().PaddingTop(2).Element(c => ComposeStatusBadge(c, _container.Status));
                });
            });

            row.ConstantItem(200).Column(col =>
            {
                col.Item().AlignRight().Row(r =>
                {
                    r.AutoItem().Width(24).Height(24).Background(Colors.Grey.Lighten2).AlignCenter().AlignMiddle()
                        .Text("📅").FontSize(12);
                    r.AutoItem().PaddingLeft(5).Column(c =>
                    {
                        c.Item().Text("Report Date").FontSize(8).FontColor(Colors.Grey.Medium);
                        c.Item().Text(DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm") + " UTC").FontSize(10).SemiBold();
                    });
                });
                col.Item().PaddingTop(5).AlignRight().Row(r =>
                {
                    r.AutoItem().Width(24).Height(24).Background(Colors.Grey.Lighten2).AlignCenter().AlignMiddle()
                        .Text("👤").FontSize(12);
                    r.AutoItem().PaddingLeft(5).Column(c =>
                    {
                        c.Item().Text("Generated By").FontSize(8).FontColor(Colors.Grey.Medium);
                        c.Item().Text(_generatedBy).FontSize(10).SemiBold();
                    });
                });
            });
        });

        container.PaddingTop(15).BorderBottom(2).BorderColor(primaryColor);
    }

    void ComposeStatusBadge(IContainer container, ContainerStatus status)
    {
        var (bgColor, textColor, text, icon) = status switch
        {
            ContainerStatus.NotStarted => (Colors.Red.Lighten2, Colors.Red.Darken2, "NOT STARTED", "🔴"),
            ContainerStatus.InProgress => (Colors.Orange.Lighten2, Colors.Orange.Darken2, "IN PROGRESS", "🟡"),
            ContainerStatus.FullyDelivered => (Colors.Green.Lighten2, Colors.Green.Darken2, "FULLY DELIVERED", "🟢"),
            _ => (Colors.Grey.Lighten2, Colors.Grey.Darken2, "UNKNOWN", "⚪")
        };

        container.Padding(5).Background(bgColor).BorderRadius(4).AlignCenter().AlignMiddle()
            .DefaultTextStyle(x => x.FontColor(textColor).FontSize(9).SemiBold())
            .Text($"{icon} {text}");
    }

    void ComposeContent(IContainer container)
    {
        container.PaddingVertical(20).Column(col =>
        {
            // Summary Cards
            col.Item().Element(ComposeSummaryCards);
            
            // Progress Bar
            col.Item().PaddingTop(20).Element(ComposeProgressBar);
            
            // Container Details
            col.Item().PaddingTop(20).Element(ComposeContainerDetails);
            
            // Vehicles Table
            col.Item().PaddingTop(20).Element(ComposeVehiclesTable);
            
            // Notes
            if (!string.IsNullOrWhiteSpace(_container.Notes))
            {
                col.Item().PaddingTop(20).Element(ComposeNotes);
            }
            
            // Signature Section
            col.Item().PaddingTop(30).Element(ComposeSignatureSection);
        });

        void ComposeSummaryCards(IContainer container)
        {
            var stats = new[]
            {
                new StatCard("Total Vehicles", _container.TotalVehicles.ToString(), Colors.Blue.Lighten2, Colors.Blue.Darken2, "🚗"),
                new StatCard("Delivered", _container.DeliveredVehicles.ToString(), Colors.Green.Lighten2, Colors.Green.Darken2, "✅"),
                new StatCard("Pending", _container.UndeliveredVehicles.ToString(), Colors.Orange.Lighten2, Colors.Orange.Darken2, "⏳"),
                new StatCard("Completion", $"{_container.CompletionPercentage:F1}%", Colors.Purple.Lighten2, Colors.Purple.Darken2, "📊")
            };

            container.Row(row =>
            {
                for (int i = 0; i < stats.Length; i++)
                {
                    var stat = stats[i];
                    row.RelativeItem().Element(c => ComposeStatCard(c, stat));
                    if (i < stats.Length - 1) row.ConstantItem(15);
                }
            });
        }

        void ComposeStatCard(IContainer container, StatCard stat)
        {
            container.Background(stat.BackgroundColor).BorderRadius(8).Padding(20).Column(col =>
            {
                col.Item().Row(r =>
                {
                    r.AutoItem().Text(stat.Icon).FontSize(18);
                    r.RelativeItem().AlignRight().Text(stat.Label).FontSize(10).FontColor(Colors.Grey.Darken1);
                });
                col.Item().PaddingTop(5).Row(r =>
                {
                    r.RelativeItem().AlignCenter().Text(stat.Value).FontSize(28).Bold().FontColor(stat.TextColor);
                });
            });
        }

        void ComposeProgressBar(IContainer container)
        {
            container.Column(col =>
            {
                col.Item().Row(r =>
                {
                    r.RelativeItem().Text("Delivery Progress").SemiBold().FontSize(12).FontColor(Colors.Grey.Darken1);
                    r.AutoItem().Text($"{_container.CompletionPercentage:F1}%").FontSize(14).Bold().FontColor(Colors.Blue.Darken2);
                });
                col.Item().PaddingTop(8).Height(12).Background(Colors.Grey.Lighten2).BorderRadius(6).OverflowHidden().Element(c =>
                {
                    c.WidthPercent(_container.CompletionPercentage).Background(Colors.Blue.Medium).BorderRadius(6);
                });
            });
        }

        void ComposeContainerDetails(IContainer container)
        {
            container.Background(Colors.Grey.Lighten4).BorderRadius(8).Padding(20).Column(col =>
            {
                col.Item().Text("Container Details").FontSize(14).Bold().FontColor(Colors.Blue.Darken2);
                col.Item().PaddingTop(10).Row(row =>
                {
                    row.RelativeItem().Column(c =>
                    {
                        AddDetailRow(c, "Container Number", _container.ContainerNumber);
                        AddDetailRow(c, "Created Date", _container.CreatedAt.ToString("yyyy-MM-dd HH:mm UTC"));
                        if (_container.StartedAt.HasValue)
                            AddDetailRow(c, "Delivery Started", _container.StartedAt.Value.ToString("yyyy-MM-dd HH:mm UTC"));
                        if (_container.CompletedAt.HasValue)
                            AddDetailRow(c, "Delivery Completed", _container.CompletedAt.Value.ToString("yyyy-MM-dd HH:mm UTC"));
                    });
                    row.RelativeItem().Column(c =>
                    {
                        AddDetailRow(c, "Total Vehicles", _container.TotalVehicles.ToString());
                        AddDetailRow(c, "Delivered", _container.DeliveredVehicles.ToString());
                        AddDetailRow(c, "Undelivered", _container.UndeliveredVehicles.ToString());
                        AddDetailRow(c, "Status", _container.Status.ToString());
                    });
                });
            });

            void AddDetailRow(IContainer c, string label, string value)
            {
                c.Item().Row(r =>
                {
                    r.AutoItem().Text(label).FontSize(10).FontColor(Colors.Grey.Medium);
                    r.RelativeItem().AlignRight().Text(value).FontSize(10).SemiBold().FontColor(Colors.Grey.Darken2);
                });
            }
        }

        void ComposeVehiclesTable(IContainer container)
        {
            if (!_vehicles.Any())
            {
                container.AlignCenter().Padding(40).Column(c =>
                {
                    c.Item().Text("📭").FontSize(48);
                    c.Item().Text("No vehicles in this container").FontSize(14).FontColor(Colors.Grey.Medium);
                });
                return;
            }

            container.Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.ConstantColumn(45);
                    columns.RelativeColumn(2.5);
                    columns.RelativeColumn(3.5);
                    columns.ConstantColumn(110);
                    columns.RelativeColumn(2);
                    columns.RelativeColumn(2);
                });

                table.Header(header =>
                {
                    var headers = new[] { "#", "VIN", "Vehicle Description", "Status", "Delivered At", "Delivered By" };
                    foreach (var h in headers)
                    {
                        header.Cell().Element(HeaderCellStyle).Text(h).SemiBold();
                    }
                });

                int index = 1;
                foreach (var vehicle in _vehicles)
                {
                    var isDelivered = vehicle.IsDelivered;
                    var bgColor = index % 2 == 0 ? Colors.Grey.Lighten4 : Colors.White;
                    var statusBg = isDelivered ? Colors.Green.Lighten2 : Colors.Red.Lighten2;
                    var statusTextColor = isDelivered ? Colors.Green.Darken2 : Colors.Red.Darken2;
                    var statusText = isDelivered ? "✅ Delivered" : "❌ Pending";

                    table.Cell().Element(c => DataCellStyle(c, bgColor)).Text(index.ToString()).FontSize(9).AlignCenter();
                    table.Cell().Element(c => DataCellStyle(c, bgColor)).Text(vehicle.Vin).FontSize(9).FontFamily("Monospace");
                    table.Cell().Element(c => DataCellStyle(c, bgColor)).Text(vehicle.Description).FontSize(9);
                    table.Cell().Element(c => DataCellStyle(c, bgColor)).Padding(5).Background(statusBg).BorderRadius(4).AlignCenter().Text(statusText).FontSize(8).FontColor(statusTextColor).SemiBold();
                    table.Cell().Element(c => DataCellStyle(c, bgColor)).Text(vehicle.DeliveredAt?.ToString("yyyy-MM-dd HH:mm") ?? "—").FontSize(9).FontColor(Colors.Grey.Medium).AlignCenter();
                    table.Cell().Element(c => DataCellStyle(c, bgColor)).Text(vehicle.DeliveredBy ?? "—").FontSize(9).FontColor(Colors.Grey.Medium).AlignCenter();

                    index++;
                }

                static IContainer HeaderCellStyle(IContainer c) => c.Padding(8).Background(Colors.Blue.Darken2).FontColor(Colors.White).FontSize(9);
                static IContainer DataCellStyle(IContainer c, string bgColor) => c.Padding(8).BorderBottom(0.5f).BorderColor(Colors.Grey.Lighten2).Background(bgColor).FontSize(9);
            });
        }

        void ComposeSignatureSection(IContainer container)
        {
            container.Column(col =>
            {
                col.Item().BorderTop(1).BorderColor(Colors.Grey.Lighten2).PaddingTop(20).Row(row =>
                {
                    row.RelativeItem().Column(c =>
                    {
                        c.Item().Height(60).BorderBottom(1).BorderColor(Colors.Grey.Medium);
                        c.Item().PaddingTop(5).Text("Authorized Signature").FontSize(10).FontColor(Colors.Grey.Medium).AlignCenter();
                        c.Item().Text("Date: _______________").FontSize(10).FontColor(Colors.Grey.Medium).AlignCenter();
                    });
                    row.ConstantItem(50);
                    row.RelativeItem().Column(c =>
                    {
                        c.Item().Height(60).BorderBottom(1).BorderColor(Colors.Grey.Medium);
                        c.Item().PaddingTop(5).Text("Receiver Signature").FontSize(10).FontColor(Colors.Grey.Medium).AlignCenter();
                        c.Item().Text("Date: _______________").FontSize(10).FontColor(Colors.Grey.Medium).AlignCenter();
                    });
                });
            });
        }
    }

    void ComposeFooter(IContainer container)
    {
        container.AlignCenter().Column(col =>
        {
            col.Item().BorderTop(1).BorderColor(Colors.Grey.Lighten2).PaddingTop(10);
            col.Item().Row(row =>
            {
                row.RelativeItem().Text(text =>
                {
                    text.Span("Page ").FontSize(8).FontColor(Colors.Grey.Medium);
                    text.CurrentPageNumber().FontSize(8).FontColor(Colors.Grey.Darken1);
                    text.Span(" of ").FontSize(8).FontColor(Colors.Grey.Medium);
                    text.TotalPages().FontSize(8).FontColor(Colors.Grey.Darken1);
                });
                row.ConstantItem(100);
                row.RelativeItem().AlignRight().Text(text =>
                {
                    text.Span($"{_companyName} | ").FontSize(8).FontColor(Colors.Grey.Medium);
                    text.Span("CONFIDENTIAL").FontSize(8).Bold().FontColor(Colors.Red.Medium);
                });
            });
        });
    }

    void ComposeNotes(IContainer container)
    {
        container.Background(Colors.Yellow.Lighten3).BorderRadius(8).Padding(15).Column(col =>
        {
            col.Item().Row(r =>
            {
                r.AutoItem().Text("📝").FontSize(14);
                r.RelativeItem().Text("Notes").FontSize(12).Bold().FontColor(Colors.Orange.Darken2);
            });
            col.Item().PaddingTop(5).Text(_container.Notes).FontSize(10).FontColor(Colors.Grey.Darken2);
        });
    }

    private record StatCard(string Label, string Value, string BackgroundColor, string TextColor, string Icon);
}

public class ContainerData
{
    public string ContainerNumber { get; set; } = "";
    public int TotalVehicles { get; set; }
    public int DeliveredVehicles { get; set; }
    public ContainerStatus Status { get; set; }
    public double CompletionPercentage { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime? StartedAt { get; set; }
    public DateTime? CompletedAt { get; set; }
    public string? Notes { get; set; }
    public int UndeliveredVehicles => TotalVehicles - DeliveredVehicles;
}

public class VehicleData
{
    public string Vin { get; set; } = "";
    public string Description { get; set; } = "";
    public bool IsDelivered { get; set; }
    public DateTime? DeliveredAt { get; set; }
    public string? DeliveredBy { get; set; }
}